baseURL = "https://manueltansini.dev/"
languageCode = 'en-us'
theme = "coming-soon"

[params]
    title = "Coming Soon Hugo" 
    description = "A simple countdown"
    favicon = "/static/favicon.ico"
    message = "COMING SOON!" 
    release = "Jan 30, 2025" 
    background = "" 

socialIcons = [
    {name = "email", url = "tansini.manuel@gmail.com"}, 
    {name = "github", url = "https://github.com/mantans"},    
] 
